"""Build a prop pitch/geometry calibration packet.

Outputs:
  docs/data/prop_pitch_geometry_packet.csv
  docs/data/fpv_model_validation_summary.csv rows with category prop_pitch_packet_*

The source rows are generated by the main model-source analysis from official
HQProp/Gemfan pages, UIUC propeller geometry TXT files, and current RotorSpec
geometry mirrors. This packet narrows those rows into a handoff table for
per-preset blade-pitch, pitch-speed, chord proxy, and 70%R pitch-angle tuning.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs" / "data"

OUTPUT = DATA / "prop_pitch_geometry_packet.csv"
SUMMARY = DATA / "fpv_model_validation_summary.csv"

PROP_GEOMETRY = DATA / "prop_geometry_pitch_reference.csv"

DRONE_CONFIG_SOURCE = "drone-sim-core/src/main/java/com/tenicana/dronecraft/sim/DroneConfig.java"
ROTOR_SPEC_SOURCE = "drone-sim-core/src/main/java/com/tenicana/dronecraft/sim/RotorSpec.java"
OFFICIAL_PROP_SOURCES = "HQProp/Gemfan official product pages listed in docs/data/prop_geometry_pitch_reference.csv"
UIUC_GEOMETRY_SOURCE = "https://m-selig.ae.illinois.edu/props/propDB.html"


def repo_path(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, object]]) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def value_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return ""
        return f"{value:.12g}"
    return str(value)


def to_float(row: dict[str, str], key: str, default: float = math.nan) -> float:
    raw = row.get(key, "")
    if raw == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def clean(values: Iterable[float]) -> list[float]:
    return [value for value in values if math.isfinite(value)]


def add_metric(
    rows: list[dict[str, str]],
    *,
    row_type: str,
    name: str,
    metric: str,
    value: object,
    unit: str,
    source_file: Path,
    source_url: str = "",
    evidence_role: str = "",
    note: str = "",
) -> None:
    rows.append(
        {
            "row_type": row_type,
            "name": name,
            "metric": metric,
            "value": value_text(value),
            "unit": unit,
            "source_file": repo_path(source_file),
            "source_url": source_url,
            "evidence_role": evidence_role,
            "note": note,
        }
    )


def add_source_inventory(packet: list[dict[str, str]]) -> None:
    sources = [
        (
            "Current_RotorSpec_default_pitch_geometry",
            f"{DRONE_CONFIG_SOURCE}; {ROTOR_SPEC_SOURCE}",
            "current_default_pitch_and_geometry_proxy",
            "Current presets without overrides use RotorSpec.defaultBladePitchMeters(radius) = max(0.01, 1.70R), or P/D = 0.85 for current radii.",
        ),
        (
            "Official_HQProp_Gemfan_pitch_mass_pages",
            OFFICIAL_PROP_SOURCES,
            "official_product_diameter_pitch_mass",
            "Official product labels and mass rows for 5-inch FPV, 3-inch/ducted, and 10-inch lift prop families.",
        ),
        (
            "UIUC_propeller_geometry_TXT_files",
            UIUC_GEOMETRY_SOURCE,
            "station_geometry_r_over_R_c_over_R_beta",
            "UIUC geometry files provide r/R, c/R, and beta station data used to derive 70%R chord and local pitch ratios.",
        ),
        (
            "Generated_prop_geometry_reference",
            repo_path(PROP_GEOMETRY),
            "wide_source_table",
            "Wide table with current presets, official prop pitch rows, UIUC summaries, raw station rows, and current-vs-reference comparisons.",
        ),
    ]
    for name, source_url, role, note in sources:
        add_metric(
            packet,
            row_type="prop_pitch_packet_source_inventory",
            name=name,
            metric="source_file",
            value=repo_path(PROP_GEOMETRY),
            unit="path",
            source_file=PROP_GEOMETRY,
            source_url=source_url,
            evidence_role=role,
            note=note,
        )


def add_current_presets(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("current_diameter_in", "in"),
        ("current_pitch_in", "in"),
        ("current_pitch_to_diameter", "ratio"),
        ("current_hover_pitch_speed_m_s", "m/s"),
        ("current_max_pitch_speed_m_s", "m/s"),
        ("current_geometric_pitch_angle_70r_deg", "deg"),
        ("rotor_blade_count", "count"),
        ("blade_pitch_source", "text"),
    ]
    for row in rows:
        if row.get("row_type") != "current_preset_pitch_geometry":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="prop_pitch_packet_current_preset",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=PROP_GEOMETRY,
                source_url=f"{DRONE_CONFIG_SOURCE}; {ROTOR_SPEC_SOURCE}",
                evidence_role="current_geometry_proxy",
                note="Mirrors current RotorSpec pitch geometry; pitch speed is ideal geometric pitch with no slip.",
            )


def add_physical_refs(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("reference_diameter_in", "in"),
        ("reference_pitch_in", "in"),
        ("reference_pitch_to_diameter", "ratio"),
        ("reference_pitch_speed_m_s_at_1000rpm", "m/s per 1000 rpm"),
        ("reference_geometric_pitch_angle_70r_deg", "deg"),
        ("rotor_blade_count", "count"),
        ("mass_g", "g"),
    ]
    for row in rows:
        if row.get("row_type") != "physical_prop_pitch_reference":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="prop_pitch_packet_official_prop_reference",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=PROP_GEOMETRY,
                source_url=row.get("source", ""),
                evidence_role="official_product_pitch_mass_reference",
                note="Official product page reference; pitch label is geometric/nominal and not a slip-corrected aerodynamic pitch.",
            )


def add_uiuc_summaries(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("geometry_station_count", "count"),
        ("reference_chord_to_radius_70r", "ratio"),
        ("reference_beta_deg_70r", "deg"),
        ("reference_local_pitch_to_diameter_70r", "ratio"),
        ("reference_planform_solidity_proxy", "ratio"),
        ("rotor_blade_count", "count"),
    ]
    for row in rows:
        if row.get("row_type") != "reference_uiuc_prop_geometry_summary":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="prop_pitch_packet_uiuc_geometry_summary",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=PROP_GEOMETRY,
                source_url=row.get("source", ""),
                evidence_role="uiuc_station_geometry_summary",
                note="70%R fields are interpolated from UIUC r/R, c/R, beta station rows.",
            )


def add_current_vs_physical(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("diameter_delta_percent", "%"),
        ("current_pitch_over_reference", "ratio"),
        ("current_pitch_to_diameter_over_reference", "ratio"),
        ("current_pitch_speed_over_reference", "ratio"),
        ("current_geometric_pitch_angle_over_reference", "ratio"),
    ]
    for row in rows:
        if row.get("row_type") != "current_vs_physical_prop_pitch_reference":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="prop_pitch_packet_current_vs_official_prop",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=PROP_GEOMETRY,
                source_url=row.get("source", ""),
                evidence_role="current_vs_official_pitch_ratio",
                note="Same-size comparison where possible; geometry check only, not measured aerodynamic pitch/slip.",
            )


def add_current_vs_uiuc(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("diameter_delta_percent", "%"),
        ("current_proxy_chord_over_reference_70r", "ratio"),
        ("current_geometric_pitch_angle_over_reference_70r", "ratio"),
        ("current_pitch_to_diameter_over_reference_local_70r", "ratio"),
    ]
    for row in rows:
        if row.get("row_type") != "current_vs_uiuc_prop_geometry_reference":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="prop_pitch_packet_current_vs_uiuc_geometry",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=PROP_GEOMETRY,
                source_url=row.get("source", ""),
                evidence_role="current_vs_uiuc_70r_geometry_ratio",
                note="Compares current representative chord and 70%R pitch angle against UIUC station geometry.",
            )


def add_crosscheck(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    current = [row for row in rows if row.get("row_type") == "current_preset_pitch_geometry"]
    physical = [row for row in rows if row.get("row_type") == "current_vs_physical_prop_pitch_reference"]
    uiuc = [row for row in rows if row.get("row_type") == "current_vs_uiuc_prop_geometry_reference"]
    uiuc_points = [row for row in rows if row.get("row_type") == "reference_uiuc_prop_geometry_point"]
    uiuc_summaries = [row for row in rows if row.get("row_type") == "reference_uiuc_prop_geometry_summary"]

    def values(source_rows: list[dict[str, str]], preset: str, key: str) -> list[float]:
        return clean(to_float(row, key) for row in source_rows if row.get("preset") == preset)

    default_pd = clean(to_float(row, "current_pitch_to_diameter") for row in current)
    racing_phys = values(physical, "racingQuad", "current_pitch_over_reference")
    racing_uiuc_angle = values(uiuc, "racingQuad", "current_geometric_pitch_angle_over_reference_70r")
    racing_uiuc_chord = values(uiuc, "racingQuad", "current_proxy_chord_over_reference_70r")
    heavy_phys = values(physical, "heavyLift", "current_pitch_over_reference")
    heavy_phys_angle = values(physical, "heavyLift", "current_geometric_pitch_angle_over_reference")
    heavy_uiuc_angle = values(uiuc, "heavyLift", "current_geometric_pitch_angle_over_reference_70r")
    heavy_uiuc_local_pd = values(uiuc, "heavyLift", "current_pitch_to_diameter_over_reference_local_70r")
    heavy_uiuc_chord = values(uiuc, "heavyLift", "current_proxy_chord_over_reference_70r")

    metrics = [
        ("current_default_pitch_to_diameter_min", min(default_pd), "ratio"),
        ("current_default_pitch_to_diameter_max", max(default_pd), "ratio"),
        ("official_prop_reference_count", len([row for row in rows if row.get("row_type") == "physical_prop_pitch_reference"]), "count"),
        ("uiuc_geometry_summary_count", len(uiuc_summaries), "count"),
        ("uiuc_geometry_station_row_count", len(uiuc_points), "count"),
        ("current_vs_official_comparison_count", len(physical), "count"),
        ("current_vs_uiuc_comparison_count", len(uiuc), "count"),
        ("racing_official_pitch_ratio_min", min(racing_phys), "ratio"),
        ("racing_official_pitch_ratio_max", max(racing_phys), "ratio"),
        ("racing_uiuc_70r_pitch_angle_ratio_min", min(racing_uiuc_angle), "ratio"),
        ("racing_uiuc_70r_pitch_angle_ratio_max", max(racing_uiuc_angle), "ratio"),
        ("racing_uiuc_70r_chord_ratio_min", min(racing_uiuc_chord), "ratio"),
        ("racing_uiuc_70r_chord_ratio_max", max(racing_uiuc_chord), "ratio"),
        ("heavy_official_pitch_ratio_min", min(heavy_phys), "ratio"),
        ("heavy_official_pitch_ratio_max", max(heavy_phys), "ratio"),
        ("heavy_official_70r_angle_ratio_min", min(heavy_phys_angle), "ratio"),
        ("heavy_official_70r_angle_ratio_max", max(heavy_phys_angle), "ratio"),
        ("heavy_uiuc_70r_pitch_angle_ratio_min", min(heavy_uiuc_angle), "ratio"),
        ("heavy_uiuc_70r_pitch_angle_ratio_max", max(heavy_uiuc_angle), "ratio"),
        ("heavy_uiuc_70r_local_pd_ratio_min", min(heavy_uiuc_local_pd), "ratio"),
        ("heavy_uiuc_70r_local_pd_ratio_max", max(heavy_uiuc_local_pd), "ratio"),
        ("heavy_uiuc_70r_chord_ratio_min", min(heavy_uiuc_chord), "ratio"),
        ("heavy_uiuc_70r_chord_ratio_max", max(heavy_uiuc_chord), "ratio"),
    ]
    for metric, value, unit in metrics:
        add_metric(
            packet,
            row_type="prop_pitch_packet_crosscheck",
            name="summary",
            metric=metric,
            value=value,
            unit=unit,
            source_file=PROP_GEOMETRY,
            source_url=f"{OFFICIAL_PROP_SOURCES}; {UIUC_GEOMETRY_SOURCE}; {ROTOR_SPEC_SOURCE}",
            evidence_role="handoff_summary",
            note="Use these summary ratios to decide which presets need explicit blade-pitch/chord overrides.",
        )


def add_method(packet: list[dict[str, str]]) -> None:
    add_metric(
        packet,
        row_type="prop_pitch_packet_method",
        name="method",
        metric="scope_and_caveat",
        value=(
            "Use this packet for geometry handoff only: nominal prop pitch labels, UIUC station beta/chord, and current "
            "RotorSpec pitch/chord proxies. Do not treat label pitch as slip-corrected aerodynamic advance, and keep "
            "large-lift prop geometry separate from the 5-inch FPV default P/D = 0.85."
        ),
        unit="text",
        source_file=PROP_GEOMETRY,
        source_url=f"{OFFICIAL_PROP_SOURCES}; {UIUC_GEOMETRY_SOURCE}",
        evidence_role="method",
    )


def build_packet() -> list[dict[str, str]]:
    source_rows = read_rows(PROP_GEOMETRY)
    packet: list[dict[str, str]] = []
    add_source_inventory(packet)
    add_current_presets(packet, source_rows)
    add_physical_refs(packet, source_rows)
    add_uiuc_summaries(packet, source_rows)
    add_current_vs_physical(packet, source_rows)
    add_current_vs_uiuc(packet, source_rows)
    add_crosscheck(packet, source_rows)
    add_method(packet)
    return packet


def sync_summary(packet_rows: Iterable[dict[str, str]]) -> int:
    existing = read_rows(SUMMARY)
    kept = [row for row in existing if not row.get("category", "").startswith("prop_pitch_packet_")]
    added: list[dict[str, str]] = []
    for row in packet_rows:
        added.append(
            {
                "category": row["row_type"],
                "name": row["name"],
                "metric": row["metric"],
                "value": row["value"],
                "unit": row["unit"],
                "source": row.get("source_url") or row.get("source_file", ""),
            }
        )
    write_csv(SUMMARY, kept + added)
    return len(added)


def main() -> None:
    packet_rows = build_packet()
    write_csv(OUTPUT, packet_rows)
    synced = sync_summary(packet_rows)
    print(f"Wrote {repo_path(OUTPUT)} with {len(packet_rows)} rows")
    print(f"Synced {synced} rows into {repo_path(SUMMARY)}")


if __name__ == "__main__":
    main()
