"""Build a wind/gust/turbulence calibration packet.

Outputs:
  docs/data/wind_gust_calibration_packet.csv
  docs/data/fpv_model_validation_summary.csv rows with category wind_gust_packet_*

The source CSV is generated by the main model-source analysis from the current
hybrid wind model, pyfly/MIL-F-8785C Dryden formulas, an open UAV wind modeling
survey, and ICAS 2020 hover-gust CFD tables. This packet narrows those rows
into one handoff table for turbulence intensity, spectral shape, and direct
rotor thrust response checks.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs" / "data"

OUTPUT = DATA / "wind_gust_calibration_packet.csv"
SUMMARY = DATA / "fpv_model_validation_summary.csv"

WIND_REFERENCE = DATA / "wind_gust_dryden_reference.csv"

DRONE_PHYSICS_SOURCE = "drone-sim-core/src/main/java/com/tenicana/dronecraft/sim/DronePhysics.java"
PYFLY_DRYDEN_URL = "https://raw.githubusercontent.com/eivindeb/pyfly/master/pyfly/dryden.py"
UAV_WIND_SURVEY_URL = "https://arxiv.org/abs/1905.09954"
ICAS_GUST_PDF_URL = "https://www.icas.org/icas_archive/ICAS2020/data/papers/ICAS2020_0482_paper.pdf"


def repo_path(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, object]]) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def value_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return ""
        return f"{value:.12g}"
    return str(value)


def to_float(row: dict[str, str], key: str, default: float = math.nan) -> float:
    raw = row.get(key, "")
    if raw == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def clean(values: Iterable[float]) -> list[float]:
    return [value for value in values if math.isfinite(value)]


def fmt_name(value: float) -> str:
    text = f"{value:.3f}".rstrip("0").rstrip(".")
    return text.replace(".", "p")


def scan_name(row: dict[str, str]) -> str:
    wind = fmt_name(to_float(row, "wind_speed_m_s"))
    dirty = fmt_name(to_float(row, "dirty_air"))
    altitude = fmt_name(to_float(row, "altitude_m"))
    return f"wind_{wind}m_s_dirty_{dirty}_alt_{altitude}m"


def add_metric(
    rows: list[dict[str, str]],
    *,
    row_type: str,
    name: str,
    metric: str,
    value: object,
    unit: str,
    source_file: Path,
    source_url: str = "",
    evidence_role: str = "",
    note: str = "",
) -> None:
    rows.append(
        {
            "row_type": row_type,
            "name": name,
            "metric": metric,
            "value": value_text(value),
            "unit": unit,
            "source_file": repo_path(source_file),
            "source_url": source_url,
            "evidence_role": evidence_role,
            "note": note,
        }
    )


def add_source_inventory(packet: list[dict[str, str]]) -> None:
    sources = [
        (
            "Current_project_hybrid_wind_model",
            DRONE_PHYSICS_SOURCE,
            "current_runtime_wind_model",
            "Current model combines mean-wind smoothing, reduced deterministic burble, and Dryden-scaled colored turbulence.",
        ),
        (
            "pyfly_Dryden_MIL_F_8785C_reference",
            PYFLY_DRYDEN_URL,
            "open_source_dryden_formula_reference",
            "pyfly exposes the low-altitude Dryden length-scale and sigma formulas used as the reference shape.",
        ),
        (
            "Open_UAV_wind_modeling_survey",
            UAV_WIND_SURVEY_URL,
            "wind_modeling_context",
            "Survey context for spatio-temporal wind fields, turbulence, and gusting in UAV simulation.",
        ),
        (
            "ICAS_2020_hover_gust_CFD",
            ICAS_GUST_PDF_URL,
            "direct_rotor_gust_thrust_response",
            "ICAS 2020 tables give hover CT changes under 10 m/s gusts from multiple inflow directions.",
        ),
    ]
    for name, source_url, role, note in sources:
        add_metric(
            packet,
            row_type="wind_gust_packet_source_inventory",
            name=name,
            metric="source_file",
            value=repo_path(WIND_REFERENCE),
            unit="path",
            source_file=WIND_REFERENCE,
            source_url=source_url,
            evidence_role=role,
            note=note,
        )


def add_current_intensity_scan(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("dirty_air", "input"),
        ("wind_speed_m_s", "m/s"),
        ("altitude_m", "m"),
        ("current_gust_scale", "scale"),
        ("current_burble_scale", "scale"),
        ("dryden_intensity_scale", "scale"),
        ("current_gust_rms_x_m_s", "m/s"),
        ("current_gust_rms_y_m_s", "m/s"),
        ("current_gust_rms_z_m_s", "m/s"),
        ("current_burble_rms_x_m_s", "m/s"),
        ("current_burble_rms_y_m_s", "m/s"),
        ("current_burble_rms_z_m_s", "m/s"),
        ("dryden_target_rms_x_m_s", "m/s"),
        ("dryden_target_rms_y_m_s", "m/s"),
        ("dryden_target_rms_z_m_s", "m/s"),
        ("current_gust_peak_x_m_s", "m/s"),
        ("current_gust_peak_y_m_s", "m/s"),
        ("current_gust_peak_z_m_s", "m/s"),
        ("dryden_sigma_u_m_s", "m/s"),
        ("dryden_sigma_w_m_s", "m/s"),
        ("current_x_rms_over_dryden_u", "ratio"),
        ("current_y_rms_over_dryden_w", "ratio"),
    ]
    for row in rows:
        if row.get("row_type") != "current_wind_gust_scan":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="wind_gust_packet_current_intensity_scan",
                name=scan_name(row),
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=WIND_REFERENCE,
                source_url=f"{DRONE_PHYSICS_SOURCE}; {PYFLY_DRYDEN_URL}",
                evidence_role="current_vs_low_altitude_dryden_intensity",
                note="Current target gust RMS includes reduced deterministic burble plus Dryden target before vehicle response/filtering.",
            )


def add_spectral_shape_scan(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("phase_a_period_s", "s"),
        ("phase_b_period_s", "s"),
        ("phase_c_period_s", "s"),
        ("gust_time_constant_s", "s"),
        ("mean_wind_time_constant_s", "s"),
        ("dryden_lu_m", "m"),
        ("dryden_lw_m", "m"),
        ("dryden_longitudinal_time_s", "s"),
        ("dryden_vertical_time_s", "s"),
        ("current_gust_corner_hz", "Hz"),
        ("current_mean_wind_corner_hz", "Hz"),
        ("dryden_u_pole_hz", "Hz"),
        ("dryden_vw_pole_hz", "Hz"),
        ("dryden_vw_zero_hz", "Hz"),
        ("current_corner_over_dryden_u_pole", "ratio"),
        ("current_corner_over_dryden_w_pole", "ratio"),
        ("current_shape_over_dryden_u_at_0_5hz", "ratio"),
        ("current_shape_over_dryden_w_at_0_5hz", "ratio"),
        ("current_shape_over_dryden_u_at_1hz", "ratio"),
        ("current_shape_over_dryden_w_at_1hz", "ratio"),
    ]
    for row in rows:
        if row.get("row_type") != "current_wind_gust_scan":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="wind_gust_packet_spectral_shape_scan",
                name=scan_name(row),
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=WIND_REFERENCE,
                source_url=f"{DRONE_PHYSICS_SOURCE}; {PYFLY_DRYDEN_URL}",
                evidence_role="spectral_shape_check",
                note="Shows whether the current one-pole gust filter is faster/slower than Dryden low-altitude poles.",
            )


def add_icas_hover_gust(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    metrics = [
        ("rpm", "rpm"),
        ("gust_speed_m_s", "m/s"),
        ("gust_direction_deg", "deg"),
        ("gust_direction_label", "label"),
        ("ct_no_wind", "CT"),
        ("ct_gust", "CT"),
        ("ct_ratio_gust_over_no_wind", "ratio"),
        ("ct_change_percent", "%"),
    ]
    for row in rows:
        if row.get("row_type") != "reference_icas_hover_gust_ct":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="wind_gust_packet_icas_hover_ct",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=WIND_REFERENCE,
                source_url=row.get("source", ICAS_GUST_PDF_URL),
                evidence_role="direct_rotor_hover_gust_ct_change",
                note=row.get("note", ""),
            )


def require_one(rows: list[dict[str, str]], predicate) -> dict[str, str]:
    found = [row for row in rows if predicate(row)]
    if len(found) != 1:
        raise LookupError(f"expected one row, found {len(found)}")
    return found[0]


def add_crosscheck(packet: list[dict[str, str]], rows: list[dict[str, str]]) -> None:
    scans = [row for row in rows if row.get("row_type") == "current_wind_gust_scan"]
    icas = [row for row in rows if row.get("row_type") == "reference_icas_hover_gust_ct"]
    representative = require_one(
        scans,
        lambda row: abs(to_float(row, "wind_speed_m_s") - 10.0) <= 1.0e-9
        and abs(to_float(row, "dirty_air") - 1.5) <= 1.0e-9,
    )

    def scan_values(key: str) -> list[float]:
        return clean(to_float(row, key) for row in scans)

    def icas_change(rpm: float, direction: str) -> float:
        row = require_one(
            icas,
            lambda item: abs(to_float(item, "rpm") - rpm) <= 1.0e-9
            and item.get("gust_direction_label") == direction,
        )
        return to_float(row, "ct_change_percent")

    metrics = [
        ("current_wind_scan_count", len(scans), "count"),
        ("icas_hover_gust_row_count", len(icas), "count"),
        ("representative_wind_speed_m_s", to_float(representative, "wind_speed_m_s"), "m/s"),
        ("representative_dirty_air", to_float(representative, "dirty_air"), "input"),
        ("representative_current_gust_rms_x_m_s", to_float(representative, "current_gust_rms_x_m_s"), "m/s"),
        ("representative_current_gust_rms_y_m_s", to_float(representative, "current_gust_rms_y_m_s"), "m/s"),
        ("representative_current_x_rms_over_dryden_u", to_float(representative, "current_x_rms_over_dryden_u"), "ratio"),
        ("representative_current_y_rms_over_dryden_w", to_float(representative, "current_y_rms_over_dryden_w"), "ratio"),
        ("representative_gust_corner_hz", to_float(representative, "current_gust_corner_hz"), "Hz"),
        ("representative_dryden_u_pole_hz", to_float(representative, "dryden_u_pole_hz"), "Hz"),
        ("representative_dryden_w_pole_hz", to_float(representative, "dryden_vw_pole_hz"), "Hz"),
        ("representative_shape_over_dryden_u_at_1hz", to_float(representative, "current_shape_over_dryden_u_at_1hz"), "ratio"),
        ("representative_shape_over_dryden_w_at_1hz", to_float(representative, "current_shape_over_dryden_w_at_1hz"), "ratio"),
        ("current_x_rms_over_dryden_u_min", min(scan_values("current_x_rms_over_dryden_u")), "ratio"),
        ("current_x_rms_over_dryden_u_max", max(scan_values("current_x_rms_over_dryden_u")), "ratio"),
        ("current_y_rms_over_dryden_w_min", min(scan_values("current_y_rms_over_dryden_w")), "ratio"),
        ("current_y_rms_over_dryden_w_max", max(scan_values("current_y_rms_over_dryden_w")), "ratio"),
        ("current_corner_over_dryden_u_pole_min", min(scan_values("current_corner_over_dryden_u_pole")), "ratio"),
        ("current_corner_over_dryden_u_pole_max", max(scan_values("current_corner_over_dryden_u_pole")), "ratio"),
        ("current_shape_over_dryden_u_at_1hz_max", max(scan_values("current_shape_over_dryden_u_at_1hz")), "ratio"),
        ("current_shape_over_dryden_w_at_1hz_max", max(scan_values("current_shape_over_dryden_w_at_1hz")), "ratio"),
        ("icas_4319rpm_downdraft_ct_change_percent", icas_change(4319.0, "-90deg"), "%"),
        ("icas_4319rpm_updraft_ct_change_percent", icas_change(4319.0, "90deg"), "%"),
        ("icas_6528rpm_downdraft_ct_change_percent", icas_change(6528.0, "-90deg"), "%"),
        ("icas_6528rpm_updraft_ct_change_percent", icas_change(6528.0, "90deg"), "%"),
        ("icas_ct_change_percent_min", min(clean(to_float(row, "ct_change_percent") for row in icas)), "%"),
        ("icas_ct_change_percent_max", max(clean(to_float(row, "ct_change_percent") for row in icas)), "%"),
    ]
    for metric, value, unit in metrics:
        add_metric(
            packet,
            row_type="wind_gust_packet_crosscheck",
            name="summary",
            metric=metric,
            value=value,
            unit=unit,
            source_file=WIND_REFERENCE,
            source_url=f"{PYFLY_DRYDEN_URL}; {UAV_WIND_SURVEY_URL}; {ICAS_GUST_PDF_URL}; {DRONE_PHYSICS_SOURCE}",
            evidence_role="handoff_summary",
            note="Use these rows to separate gust-field RMS matching from Dryden spectral shape and direct rotor thrust perturbation.",
        )


def add_method(packet: list[dict[str, str]]) -> None:
    add_metric(
        packet,
        row_type="wind_gust_packet_method",
        name="method",
        metric="scope_and_caveat",
        value=(
            "Use this packet as a wind-field and gust-response handoff. The Dryden rows check low-altitude "
            "turbulence intensity and filter shape; the ICAS rows show direct rotor CT changes under gust direction. "
            "Do not collapse deterministic dirty-air burble, atmospheric Dryden turbulence, and rotor inflow CT "
            "perturbation into one coefficient."
        ),
        unit="text",
        source_file=WIND_REFERENCE,
        source_url=f"{PYFLY_DRYDEN_URL}; {UAV_WIND_SURVEY_URL}; {ICAS_GUST_PDF_URL}",
        evidence_role="method",
    )


def build_packet() -> list[dict[str, str]]:
    source_rows = read_rows(WIND_REFERENCE)
    packet: list[dict[str, str]] = []
    add_source_inventory(packet)
    add_current_intensity_scan(packet, source_rows)
    add_spectral_shape_scan(packet, source_rows)
    add_icas_hover_gust(packet, source_rows)
    add_crosscheck(packet, source_rows)
    add_method(packet)
    return packet


def sync_summary(packet_rows: Iterable[dict[str, str]]) -> int:
    existing = read_rows(SUMMARY)
    kept = [row for row in existing if not row.get("category", "").startswith("wind_gust_packet_")]
    added: list[dict[str, str]] = []
    for row in packet_rows:
        added.append(
            {
                "category": row["row_type"],
                "name": row["name"],
                "metric": row["metric"],
                "value": row["value"],
                "unit": row["unit"],
                "source": row.get("source_url") or row.get("source_file", ""),
            }
        )
    write_csv(SUMMARY, kept + added)
    return len(added)


def main() -> None:
    packet_rows = build_packet()
    write_csv(OUTPUT, packet_rows)
    synced = sync_summary(packet_rows)
    print(f"Wrote {repo_path(OUTPUT)} with {len(packet_rows)} rows")
    print(f"Synced {synced} rows into {repo_path(SUMMARY)}")


if __name__ == "__main__":
    main()
