"""Build a motor/ESC thermal calibration packet.

Outputs:
  docs/data/motor_thermal_packet.csv
  docs/data/fpv_model_validation_summary.csv rows with category motor_thermal_packet_*

The source rows are generated by the main model-source analysis from public
U8/Kv100 dyno maps, Mini Quad Test Bench FPV motor metadata, copper winding
temperature references, and current project thermal/electrical mirrors. This
packet reshapes the wide thermal table into a narrow handoff table for tuning
motor/ESC thermal rise, cooling, and hot-winding resistance behavior.
"""

from __future__ import annotations

import csv
import math
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "docs" / "data"

OUTPUT = DATA / "motor_thermal_packet.csv"
SUMMARY = DATA / "fpv_model_validation_summary.csv"

MOTOR_THERMAL = DATA / "motor_esc_thermal_reference.csv"
ESC_ELECTRICAL = DATA / "esc_electrical_dynamics_reference.csv"

DRONE_CONFIG_SOURCE = "drone-sim-core/src/main/java/com/tenicana/dronecraft/sim/DroneConfig.java"
U8_SOURCE = "https://github.com/thhsieh/U8-Kv100-Dyno-Data"
MQTB_SOURCE = "https://www.miniquadtestbench.com/assets/components/motordata/motorinfo.php?uid=259"
COPPER_SOURCE = "https://www.copper.org/publications/newsletters/innovations/2001/08/intro_fac.html"
MOTOR_INSULATION_SOURCE = "https://www.theaemt.com/resource/insulation-classes-for-electric-motors.html"
INFINEON_MOSFET_SOURCE = "https://www.infineon.com/part/IRL40SC228"

REFERENCE_AMBIENT_C = 25.0


def repo_path(path: Path) -> str:
    return path.resolve().relative_to(ROOT).as_posix()


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: Iterable[dict[str, object]]) -> None:
    rows = list(rows)
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def value_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return ""
        return f"{value:.12g}"
    return str(value)


def to_float(row: dict[str, str], key: str, default: float = math.nan) -> float:
    raw = row.get(key, "")
    if raw == "":
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def require_one(rows: list[dict[str, str]], predicate) -> dict[str, str]:
    found = [row for row in rows if predicate(row)]
    if len(found) != 1:
        raise LookupError(f"expected one row, found {len(found)}")
    return found[0]


def add_metric(
    rows: list[dict[str, str]],
    *,
    row_type: str,
    name: str,
    metric: str,
    value: object,
    unit: str,
    source_file: Path,
    source_url: str = "",
    evidence_role: str = "",
    note: str = "",
) -> None:
    rows.append(
        {
            "row_type": row_type,
            "name": name,
            "metric": metric,
            "value": value_text(value),
            "unit": unit,
            "source_file": repo_path(source_file),
            "source_url": source_url,
            "evidence_role": evidence_role,
            "note": note,
        }
    )


def add_source_inventory(packet: list[dict[str, str]]) -> None:
    sources = [
        (
            "U8_Kv100_open_dyno_temperature_loss_maps",
            MOTOR_THERMAL,
            U8_SOURCE,
            "open_bldc_temperature_loss_efficiency_map",
            "Larger U8/Kv100 motor/driver dyno maps; use for BLDC thermal direction and loss scale, not FPV 2306 coefficients.",
        ),
        (
            "MQTB_Emax_Eco_2306_FPV_motor_metadata",
            MOTOR_THERMAL,
            MQTB_SOURCE,
            "fpv_2306_hardware_class_metadata",
            "FPV-class motor KV, mass, stator, ESC rating, logger rate, and ambient metadata; no winding or ESC temperature rise.",
        ),
        (
            "Current_project_motor_ESC_thermal_model",
            MOTOR_THERMAL,
            DRONE_CONFIG_SOURCE,
            "current_thermal_limit_cooling_proxy",
            "Mirrors current thermal rise, cooling, motor/ESC limit, cutoff, and steady-rise formulas.",
        ),
        (
            "Current_project_ESC_electrical_stress_model",
            ESC_ELECTRICAL,
            DRONE_CONFIG_SOURCE,
            "current_power_current_headroom_proxy",
            "Mirrors current inferred KV, headroom, phase-current proxy, and shaft-power current proxy.",
        ),
        (
            "Copper_winding_temperature_coefficient",
            MOTOR_THERMAL,
            COPPER_SOURCE,
            "copper_resistance_temperature_shape",
            "Used for hot-winding resistance scaling; supports direction and slope, not motor cooling constants.",
        ),
        (
            "Motor_insulation_and_MOSFET_context",
            MOTOR_THERMAL,
            f"{MOTOR_INSULATION_SOURCE}; {INFINEON_MOSFET_SOURCE}",
            "thermal_limit_context",
            "Useful context for plausible motor/ESC temperature limits, but not direct FPV bench telemetry.",
        ),
    ]
    for name, source_file, source_url, role, note in sources:
        add_metric(
            packet,
            row_type="motor_thermal_packet_source_inventory",
            name=name,
            metric="source_file",
            value=repo_path(source_file),
            unit="path",
            source_file=source_file,
            source_url=source_url,
            evidence_role=role,
            note=note,
        )


def add_u8_dyno(packet: list[dict[str, str]], thermal_rows: list[dict[str, str]]) -> None:
    metrics = [
        ("voltage_v", "V"),
        ("temperature_sample_count", "count"),
        ("temperature_mean_c", "C"),
        ("temperature_max_c", "C"),
        ("loss_mean_w", "W"),
        ("loss_max_w", "W"),
        ("motor_efficiency_mean", "fraction"),
        ("motor_efficiency_max", "fraction"),
        ("driver_efficiency_mean", "fraction"),
        ("driver_efficiency_max", "fraction"),
        ("rpm_max", "rpm"),
        ("torque_max_nm", "N*m"),
        ("current_max_a", "A"),
        ("max_temp_current_a", "A"),
        ("max_temp_rpm", "rpm"),
        ("max_temp_torque_nm", "N*m"),
    ]
    for row in thermal_rows:
        if row.get("row_type") != "u8_dyno_processed":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="motor_thermal_packet_u8_dyno_summary",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=MOTOR_THERMAL,
                source_url=U8_SOURCE,
                evidence_role="larger_open_bldc_dyno_temperature_loss_anchor",
                note="Cross-class thermal/loss reference; not direct FPV 2306 motor calibration.",
            )


def add_mqtb_metadata(packet: list[dict[str, str]], thermal_rows: list[dict[str, str]]) -> None:
    row = require_one(thermal_rows, lambda item: item.get("row_type") == "reference_mqtb_fpv_motor_metadata")
    metrics = [
        ("tested_kv_rpm_per_v", "rpm/V"),
        ("motor_weight_g", "g"),
        ("stator_diameter_mm", "mm"),
        ("stator_height_mm", "mm"),
        ("stator_volume_proxy_mm3", "mm^3"),
        ("esc", "text"),
        ("esc_current_rating_a", "A"),
        ("ambient_temp_min_c", "C"),
        ("ambient_temp_max_c", "C"),
        ("logger_rate_ms", "ms"),
    ]
    for metric, unit in metrics:
        add_metric(
            packet,
            row_type="motor_thermal_packet_mqtb_metadata",
            name=row["name"],
            metric=metric,
            value=row.get(metric, ""),
            unit=unit,
            source_file=MOTOR_THERMAL,
            source_url=MQTB_SOURCE,
            evidence_role="fpv_2306_hardware_class_anchor_no_temperature_rise",
            note="Use for FPV motor/ESC class plausibility; page does not report winding or ESC temperature rise.",
        )


def add_current_thermal(packet: list[dict[str, str]], thermal_rows: list[dict[str, str]]) -> None:
    metrics = [
        ("thermal_rise_c_s", "C/s"),
        ("cooling_rate_s", "1/s"),
        ("motor_limit_c", "C"),
        ("motor_cutoff_c", "C"),
        ("esc_limit_c", "C"),
        ("esc_cutoff_c", "C"),
        ("min_thermal_thrust_limit", "fraction"),
        ("motor_base_time_constant_s", "s"),
        ("motor_full_wash_time_constant_s", "s"),
        ("motor_full_10m_s_time_constant_s", "s"),
        ("motor_full_steady_rise_c", "C"),
        ("motor_hover_steady_rise_proxy_c", "C"),
        ("esc_full_current_steady_rise_proxy_c", "C"),
        ("inferred_winding_resistance_25c_ohm", "ohm"),
        ("winding_resistance_scale_at_limit", "ratio"),
        ("winding_resistance_scale_at_cutoff", "ratio"),
        ("motor_limit_scale_at_midpoint", "fraction"),
        ("esc_limit_scale_at_midpoint", "fraction"),
    ]
    for row in thermal_rows:
        if row.get("row_type") != "current_preset_thermal":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="motor_thermal_packet_current_preset",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=MOTOR_THERMAL,
                source_url=DRONE_CONFIG_SOURCE,
                evidence_role="current_model_thermal_proxy",
                note="Current-code steady-rise proxy under sea-level unobstructed conditions; not a measured temperature trace.",
            )


def add_electrical_stress(packet: list[dict[str, str]], electrical_rows: list[dict[str, str]]) -> None:
    metrics = [
        ("inferred_kv_rpm_per_v", "rpm/V"),
        ("per_motor_current_limit_a", "A"),
        ("hover_power_current_a", "A"),
        ("max_power_current_a", "A"),
        ("max_power_current_over_limit", "ratio"),
        ("max_phase_current_proxy_a", "A"),
        ("max_voltage_headroom", "fraction"),
        ("max_desync_headroom_stress", "fraction"),
    ]
    for row in electrical_rows:
        if row.get("row_type") != "current_preset":
            continue
        for metric, unit in metrics:
            add_metric(
                packet,
                row_type="motor_thermal_packet_electrical_stress",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=ESC_ELECTRICAL,
                source_url=DRONE_CONFIG_SOURCE,
                evidence_role="current_electrical_stress_input_to_thermal_model",
                note="Power-current proxy is DC battery-current sanity; phase current is torque/Kt and not pack current.",
            )


def add_racing_crosscheck(
    packet: list[dict[str, str]],
    thermal_rows: list[dict[str, str]],
    electrical_rows: list[dict[str, str]],
) -> None:
    racing_thermal = require_one(
        thermal_rows,
        lambda row: row.get("row_type") == "current_preset_thermal" and row.get("name") == "racingQuad",
    )
    racing_mqtb = require_one(
        thermal_rows,
        lambda row: row.get("row_type") == "current_vs_mqtb_fpv_motor_metadata" and row.get("name") == "racingQuad",
    )
    racing_electrical = require_one(
        electrical_rows,
        lambda row: row.get("row_type") == "current_preset" and row.get("name") == "racingQuad",
    )
    u8_rows = [row for row in thermal_rows if row.get("row_type") == "u8_dyno_processed"]
    u8_max_temp = max(to_float(row, "temperature_max_c") for row in u8_rows)
    u8_max_loss = max(to_float(row, "loss_max_w") for row in u8_rows)
    u8_max_rise_vs_25c = u8_max_temp - REFERENCE_AMBIENT_C

    full_rise = to_float(racing_thermal, "motor_full_steady_rise_c")
    hover_rise = to_float(racing_thermal, "motor_hover_steady_rise_proxy_c")
    esc_full_rise = to_float(racing_thermal, "esc_full_current_steady_rise_proxy_c")
    motor_limit = to_float(racing_thermal, "motor_limit_c")
    motor_cutoff = to_float(racing_thermal, "motor_cutoff_c")
    esc_limit = to_float(racing_thermal, "esc_limit_c")
    esc_cutoff = to_float(racing_thermal, "esc_cutoff_c")

    metrics = [
        ("reference_ambient_c", REFERENCE_AMBIENT_C, "C", "assumed_ambient_for_derived_absolute_temperature"),
        ("u8_open_dyno_max_temperature_c", u8_max_temp, "C", "cross_class_u8_dyno_reference"),
        ("u8_open_dyno_max_loss_w", u8_max_loss, "W", "cross_class_u8_dyno_reference"),
        ("u8_max_temperature_rise_vs_25c", u8_max_rise_vs_25c, "C", "cross_class_u8_dyno_reference"),
        ("current_full_power_motor_absolute_temp_at_25c", REFERENCE_AMBIENT_C + full_rise, "C", "current_model_racingquad"),
        ("current_hover_motor_absolute_temp_at_25c", REFERENCE_AMBIENT_C + hover_rise, "C", "current_model_racingquad"),
        ("current_full_esc_absolute_temp_at_25c", REFERENCE_AMBIENT_C + esc_full_rise, "C", "current_model_racingquad"),
        ("current_full_motor_rise_over_motor_limit_margin", full_rise / max(motor_limit - REFERENCE_AMBIENT_C, 1e-9), "ratio", "current_model_racingquad"),
        ("current_full_motor_rise_over_motor_cutoff_margin", full_rise / max(motor_cutoff - REFERENCE_AMBIENT_C, 1e-9), "ratio", "current_model_racingquad"),
        ("current_full_esc_rise_over_esc_limit_margin", esc_full_rise / max(esc_limit - REFERENCE_AMBIENT_C, 1e-9), "ratio", "current_model_racingquad"),
        ("current_full_esc_rise_over_esc_cutoff_margin", esc_full_rise / max(esc_cutoff - REFERENCE_AMBIENT_C, 1e-9), "ratio", "current_model_racingquad"),
        ("current_full_motor_rise_over_u8_max_rise", full_rise / max(u8_max_rise_vs_25c, 1e-9), "ratio", "cross_class_u8_dyno_comparison"),
        ("current_hover_motor_rise_over_u8_max_rise", hover_rise / max(u8_max_rise_vs_25c, 1e-9), "ratio", "cross_class_u8_dyno_comparison"),
        ("current_inferred_kv_over_mqtb_tested_kv", to_float(racing_mqtb, "inferred_kv_over_mqtb_tested_kv"), "ratio", "fpv_2306_hardware_class_anchor"),
        ("current_per_motor_limit_over_mqtb_esc_rating", to_float(racing_mqtb, "per_motor_current_limit_over_mqtb_esc_rating"), "ratio", "fpv_2306_hardware_class_anchor"),
        ("current_max_power_current_over_limit", to_float(racing_electrical, "max_power_current_over_limit"), "ratio", "current_electrical_stress_input_to_thermal_model"),
        ("current_max_power_current_a", to_float(racing_electrical, "max_power_current_a"), "A", "current_electrical_stress_input_to_thermal_model"),
    ]
    for metric, value, unit, role in metrics:
        add_metric(
            packet,
            row_type="motor_thermal_packet_racingquad_crosscheck",
            name="racingQuad",
            metric=metric,
            value=value,
            unit=unit,
            source_file=MOTOR_THERMAL,
            source_url=f"{U8_SOURCE}; {MQTB_SOURCE}; {DRONE_CONFIG_SOURCE}",
            evidence_role=role,
            note="Cross-source handoff row; U8 is larger-motor dyno evidence, MQTB is FPV-class metadata, and current temperatures are model proxies.",
        )


def add_copper_scale(packet: list[dict[str, str]], thermal_rows: list[dict[str, str]]) -> None:
    for row in thermal_rows:
        if row.get("row_type") != "copper_resistance_scale":
            continue
        for metric, unit in [("temperature_c", "C"), ("resistance_scale_vs_25c", "ratio")]:
            add_metric(
                packet,
                row_type="motor_thermal_packet_copper_resistance_scale",
                name=row["name"],
                metric=metric,
                value=row.get(metric, ""),
                unit=unit,
                source_file=MOTOR_THERMAL,
                source_url=COPPER_SOURCE,
                evidence_role="hot_winding_resistance_shape",
                note="Copper coefficient supports hot-winding resistance scaling direction; cooling and heat capacity still need motor-specific data.",
            )


def add_method(packet: list[dict[str, str]]) -> None:
    add_metric(
        packet,
        row_type="motor_thermal_packet_method",
        name="method",
        metric="scope_and_caveat",
        value=(
            "Use this packet to separate hardware class, electrical stress, thermal limit/cutoff settings, and measured "
            "temperature/loss evidence. U8 rows are cross-class BLDC dyno anchors; MQTB rows are FPV-class metadata "
            "without temperature rise; current steady-rise rows remain model proxies until FPV thermocouple/IR telemetry is found."
        ),
        unit="text",
        source_file=MOTOR_THERMAL,
        source_url=f"{U8_SOURCE}; {MQTB_SOURCE}",
        evidence_role="method",
    )


def build_packet() -> list[dict[str, str]]:
    thermal_rows = read_rows(MOTOR_THERMAL)
    electrical_rows = read_rows(ESC_ELECTRICAL)

    packet: list[dict[str, str]] = []
    add_source_inventory(packet)
    add_u8_dyno(packet, thermal_rows)
    add_mqtb_metadata(packet, thermal_rows)
    add_current_thermal(packet, thermal_rows)
    add_electrical_stress(packet, electrical_rows)
    add_racing_crosscheck(packet, thermal_rows, electrical_rows)
    add_copper_scale(packet, thermal_rows)
    add_method(packet)
    return packet


def sync_summary(packet_rows: Iterable[dict[str, str]]) -> int:
    existing = read_rows(SUMMARY)
    kept = [row for row in existing if not row.get("category", "").startswith("motor_thermal_packet_")]
    added: list[dict[str, str]] = []
    for row in packet_rows:
        added.append(
            {
                "category": row["row_type"],
                "name": row["name"],
                "metric": row["metric"],
                "value": row["value"],
                "unit": row["unit"],
                "source": row.get("source_url") or row.get("source_file", ""),
            }
        )
    write_csv(SUMMARY, kept + added)
    return len(added)


def main() -> None:
    packet_rows = build_packet()
    write_csv(OUTPUT, packet_rows)
    synced = sync_summary(packet_rows)
    print(f"Wrote {repo_path(OUTPUT)} with {len(packet_rows)} rows")
    print(f"Synced {synced} rows into {repo_path(SUMMARY)}")


if __name__ == "__main__":
    main()
