#!/usr/bin/env python3
"""Compare a complete 2.5D zero-thickness half-plane solve with exact BTMS.

The rigid screen is represented by blocked x-flux faces rather than solid
cells, so both sides remain fluid and the exterior wedge angle is exactly 2pi
in the continuum geometry.  Each axial-wavenumber node is solved numerically.
The fixed BTMS fixture is generated by the repository's independent
BtmsInfiniteWedgeReference through the btmsReference Gradle task.
"""

from __future__ import annotations

import argparse
import gc
import json
import math
import time

import numpy as np
from numpy.polynomial.legendre import leggauss

from validate_2p5d_helmholtz import (
    HelmholtzGrid,
    PhysicalPoint,
    PmlHelmholtz2d,
    SPEED_OF_SOUND_METERS_PER_SECOND,
)


EVANESCENT_DECAY_ARGUMENT = 40.0
BTMS_FREQUENCY_HZ = 1_000.0
BTMS_RAW_REAL = 0.045013459483286160
BTMS_RAW_IMAGINARY = 0.23855846886893495
BTMS_SOURCE_RADIUS_M = 0.6324555320336759
BTMS_RECEIVER_RADIUS_M = 0.6324555320336759
BTMS_SOURCE_AZIMUTH_RAD = 5.034139534781332
BTMS_RECEIVER_AZIMUTH_RAD = 1.2490457723982544


def transformed_halfplane_pressure(
    points_per_wavelength: int,
    nodes_per_branch: int,
) -> tuple[complex, dict]:
    frequency_hz = BTMS_FREQUENCY_HZ
    base_cell_size_m = (
        SPEED_OF_SOUND_METERS_PER_SECOND / frequency_hz / 16.0
    )
    cell_size_m = (
        SPEED_OF_SOUND_METERS_PER_SECOND
        / frequency_hz
        / points_per_wavelength
    )
    scale = points_per_wavelength / 16.0

    def scaled(base_index: int) -> int:
        value = base_index * scale
        rounded = round(value)
        if abs(value - rounded) > 1.0e-12:
            raise ValueError(
                "points_per_wavelength must preserve the validation grid"
            )
        return int(rounded)

    wall_face_index = scaled(120)
    edge_last_z = scaled(100)
    intended_wall_x_m = (120.0 + 0.5) * base_cell_size_m
    intended_edge_z_m = (100.0 + 0.5) * base_cell_size_m
    origin_x_m = intended_wall_x_m - (
        wall_face_index + 0.5
    ) * cell_size_m
    origin_z_m = intended_edge_z_m - (
        edge_last_z + 0.5
    ) * cell_size_m
    grid = HelmholtzGrid(
        width_cells=scaled(200) + 1,
        height_cells=scaled(160) + 1,
        cell_size_m=cell_size_m,
        pml_width_cells=scaled(20),
        pml_target_nepers=8.0,
        origin_x_m=origin_x_m,
        origin_z_m=origin_z_m,
    )
    blocked_x_faces = np.zeros(
        (grid.height_cells, grid.width_cells - 1),
        dtype=bool,
    )
    blocked_x_faces[: edge_last_z + 1, wall_face_index] = True
    source = PhysicalPoint(
        intended_wall_x_m - 0.6,
        intended_edge_z_m - 0.2,
    )
    receiver = PhysicalPoint(
        intended_wall_x_m + 0.6,
        intended_edge_z_m - 0.2,
    )
    source_radius_m = math.hypot(
        source.x_m - intended_wall_x_m,
        source.z_m - intended_edge_z_m,
    )
    receiver_radius_m = math.hypot(
        receiver.x_m - intended_wall_x_m,
        receiver.z_m - intended_edge_z_m,
    )
    if abs(source_radius_m - BTMS_SOURCE_RADIUS_M) > 1.0e-12:
        raise AssertionError("source radius no longer matches BTMS fixture")
    if abs(receiver_radius_m - BTMS_RECEIVER_RADIUS_M) > 1.0e-12:
        raise AssertionError("receiver radius no longer matches BTMS fixture")

    wave_number = (
        2.0
        * math.pi
        * frequency_hz
        / SPEED_OF_SOUND_METERS_PER_SECOND
    )
    abscissas, weights = leggauss(nodes_per_branch)
    solve_count = 0
    solve_seconds = 0.0

    def solve_at_axial_wavenumber(axial_wavenumber: float) -> complex:
        nonlocal solve_count, solve_seconds
        started = time.perf_counter()
        solver = PmlHelmholtz2d(
            grid,
            frequency_hz,
            axial_wavenumber,
            blocked_x_faces=blocked_x_faces,
        )
        solution = solver.solve_physical([source])
        value = solver.value_physical(solution, receiver)
        solve_seconds += time.perf_counter() - started
        solve_count += 1
        del solution
        del solver
        gc.collect()
        return value

    propagating = 0.0j
    for abscissa, weight in zip(abscissas, weights, strict=True):
        theta = 0.25 * math.pi * (abscissa + 1.0)
        theta_weight = 0.25 * math.pi * weight
        axial_wavenumber = wave_number * math.sin(theta)
        propagating += (
            theta_weight
            * wave_number
            * math.cos(theta)
            * solve_at_axial_wavenumber(axial_wavenumber)
        )

    minimum_transverse_distance_m = min(
        source_radius_m,
        receiver_radius_m,
    )
    maximum_u = math.asinh(
        EVANESCENT_DECAY_ARGUMENT
        / (wave_number * minimum_transverse_distance_m)
    )
    evanescent = 0.0j
    for abscissa, weight in zip(abscissas, weights, strict=True):
        u = 0.5 * maximum_u * (abscissa + 1.0)
        u_weight = 0.5 * maximum_u * weight
        axial_wavenumber = wave_number * math.cosh(u)
        evanescent += (
            u_weight
            * wave_number
            * math.sinh(u)
            * solve_at_axial_wavenumber(axial_wavenumber)
        )

    reconstructed_physical_green = (propagating + evanescent) / math.pi
    # BTMS uses a 1/r propagation normalization.  The PDE Green function is
    # exp(+ikr)/(4*pi*r), so multiply by 4*pi.  BTMS uses exp(-ikr), hence the
    # comparison fixture is conjugated later rather than silently changing
    # either solver's time convention.
    reconstructed_btms_normalization = (
        4.0 * math.pi * reconstructed_physical_green
    )
    diagnostics = {
        "frequency_hz": frequency_hz,
        "points_per_wavelength": points_per_wavelength,
        "nodes_per_branch": nodes_per_branch,
        "solve_count": solve_count,
        "solve_seconds": solve_seconds,
        "mean_seconds_per_solve": solve_seconds / solve_count,
        "unknowns_per_solve": int(
            (grid.width_cells - 2) * (grid.height_cells - 2)
        ),
        "source_radius_m": source_radius_m,
        "receiver_radius_m": receiver_radius_m,
        "source_azimuth_rad": BTMS_SOURCE_AZIMUTH_RAD,
        "receiver_azimuth_rad": BTMS_RECEIVER_AZIMUTH_RAD,
        "exterior_wedge_angle_rad": 2.0 * math.pi,
        "wall_x_m": intended_wall_x_m,
        "edge_z_m": intended_edge_z_m,
        "origin_x_m": origin_x_m,
        "origin_z_m": origin_z_m,
        "maximum_evanescent_u": maximum_u,
    }
    return reconstructed_btms_normalization, diagnostics


def complex_error(actual: complex, expected: complex) -> tuple[float, float]:
    ratio = actual / expected
    return (
        20.0 * math.log10(abs(ratio)),
        math.degrees(float(np.angle(ratio))),
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate a 2.5D half-plane against exact BTMS."
    )
    parser.add_argument(
        "--points-per-wavelength",
        type=int,
        default=24,
    )
    parser.add_argument("--nodes", type=int, default=18)
    parser.add_argument("--refined-nodes", type=int, default=24)
    parser.add_argument("--json", action="store_true")
    arguments = parser.parse_args()
    if arguments.points_per_wavelength < 16:
        parser.error("--points-per-wavelength must be at least 16")
    if arguments.nodes < 4:
        parser.error("--nodes must be at least 4")
    if arguments.refined_nodes <= arguments.nodes:
        parser.error("--refined-nodes must exceed --nodes")

    try:
        coarse, coarse_diagnostics = transformed_halfplane_pressure(
            arguments.points_per_wavelength,
            arguments.nodes,
        )
        refined, refined_diagnostics = transformed_halfplane_pressure(
            arguments.points_per_wavelength,
            arguments.refined_nodes,
        )
    except ValueError as error:
        parser.error(str(error))
    btms_conjugated = complex(BTMS_RAW_REAL, -BTMS_RAW_IMAGINARY)
    magnitude_error_db, phase_error_degrees = complex_error(
        refined,
        btms_conjugated,
    )
    refinement_magnitude_delta_db, refinement_phase_delta_degrees = (
        complex_error(refined, coarse)
    )
    passed = (
        abs(magnitude_error_db) <= 1.0
        and abs(phase_error_degrees) <= 10.0
        and abs(refinement_magnitude_delta_db) <= 0.5
        and abs(refinement_phase_delta_degrees) <= 5.0
    )
    report = {
        "btms_fixture": {
            "generator": (
                "./gradlew :computational-acoustics-core:btmsReference"
            ),
            "time_convention": "exp(-ikr)",
            "raw_real": BTMS_RAW_REAL,
            "raw_imaginary": BTMS_RAW_IMAGINARY,
            "normalized_db": -10.254967474596132,
        },
        "wave_solver": {
            "time_convention": "exp(+ikr)",
            "normalization": "4*pi times physical Green function",
            "geometry": "zero-thickness rigid half-plane via blocked flux faces",
        },
        "coarse": coarse_diagnostics,
        "refined": refined_diagnostics,
        "result": {
            "magnitude_error_db": magnitude_error_db,
            "phase_error_degrees": phase_error_degrees,
            "refinement_magnitude_delta_db": (
                refinement_magnitude_delta_db
            ),
            "refinement_phase_delta_degrees": (
                refinement_phase_delta_degrees
            ),
        },
        "gates": {
            "magnitude_error_db": 1.0,
            "phase_error_degrees": 10.0,
            "refinement_magnitude_delta_db": 0.5,
            "refinement_phase_delta_degrees": 5.0,
        },
        "passed": passed,
    }
    if arguments.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(
            "2.5D BTMS half-plane: "
            f"passed={passed} "
            f"error={magnitude_error_db:+.6f} dB/"
            f"{phase_error_degrees:+.6f} deg "
            f"refinement={refinement_magnitude_delta_db:+.6f} dB/"
            f"{refinement_phase_delta_degrees:+.6f} deg "
            f"solves={coarse_diagnostics['solve_count'] + refined_diagnostics['solve_count']} "
            f"seconds={coarse_diagnostics['solve_seconds'] + refined_diagnostics['solve_seconds']:.3f}"
        )
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
