package com.tenicana.dronecraft.sim;

import java.util.ArrayList;
import java.util.List;

public final class PropellerArchiveCtCpJLookupReviewedGridInput {
	public static final String SOURCE_ID =
			"User-Propeller-Archive-CT-CP-J-Lookup-Reviewed-Grid-Input-Packet";
	public static final String CAVEAT =
			"CT/CP/J lookup reviewed grid input expands the scattered-fit execution handoff into exact J/RPM slots the lookup runner must receive after review; it declares no CT/CP payload values, imports no raw rows, and never enables runtime coupling or gameplay auto-apply.";
	public static final int SOURCE_REFERENCE_ROW_COUNT = 9;
	public static final int GRID_INPUT_FIELD_ROW_COUNT = 18;
	public static final int GRID_INPUT_SLOT_ROW_COUNT =
			PropellerArchiveCtCpJLookupInterpolationPolicy.audit()
					.summary()
					.minimumPostReviewPerformanceNeighborRows();
	public static final int SUMMARY_ROW_COUNT = 19;
	public static final int METHOD_ROW_COUNT = 1;
	public static final int PACKET_ROW_COUNT = SOURCE_REFERENCE_ROW_COUNT
			+ GRID_INPUT_FIELD_ROW_COUNT
			+ GRID_INPUT_SLOT_ROW_COUNT
			+ SUMMARY_ROW_COUNT
			+ METHOD_ROW_COUNT;
	public static final String NEXT_REQUIRED_ACTION =
			"fill-reviewed-grid-input-slots-with-reviewed-ct-cp-payloads-before-lookup-run";

	private static final double SLOT_HALF_WINDOW_FRACTION = 0.10;

	private static final List<ReviewedGridInputField> FIELDS = List.of(
			new ReviewedGridInputField("preset_name", "text", true,
					"scattered-fit execution handoff", "join grid slot to DroneConfig preset", false, false),
			new ReviewedGridInputField("case_name", "text", true,
					"lookup query envelope", "join grid slot to query case", false, false),
			new ReviewedGridInputField("slot_id", "text", true,
					"reviewed grid slot manifest", "provide stable lookup row identifier", false, false),
			new ReviewedGridInputField("slot_kind", "text", true,
					"interpolation policy", "separate static anchor, bilinear, and high-RPM edge slots", false, false),
			new ReviewedGridInputField("slot_coordinate_role", "text", true,
					"interpolation policy", "describe lower/upper J/RPM corner role", false, false),
			new ReviewedGridInputField("query_advance_ratio_j", "J", true,
					"lookup query envelope", "trace slot back to requested J", false, false),
			new ReviewedGridInputField("query_rpm", "rpm", true,
					"lookup query envelope", "trace slot back to requested RPM", false, false),
			new ReviewedGridInputField("slot_advance_ratio_j", "J", true,
					"reviewed grid slot manifest", "supply execution-grid J coordinate", false, false),
			new ReviewedGridInputField("slot_rpm", "rpm", true,
					"reviewed grid slot manifest", "supply execution-grid RPM coordinate", false, false),
			new ReviewedGridInputField("minimum_performance_neighbor_rows", "count", true,
					"interpolation policy", "prove slot count matches lookup requirement", false, false),
			new ReviewedGridInputField("execution_input_source_kind", "text", true,
					"scattered-fit execution handoff", "route static anchors and fitted slots separately", false, false),
			new ReviewedGridInputField("direct_neighbor_binding_ready", "boolean", true,
					"scattered-fit execution handoff", "allow exact static-anchor payload after review", false, false),
			new ReviewedGridInputField("scattered_fit_required", "boolean", true,
					"scattered-fit execution handoff", "mark slots that must be generated by reviewed fit", false, false),
			new ReviewedGridInputField("archive_curve_shape_guard_passed", "boolean", true,
					"archive curve-shape review", "carry CT/CP/J curve-shape guard into lookup input", false, false),
			new ReviewedGridInputField("coefficient_payload_reviewed", "boolean", true,
					"manual coefficient review", "block unreviewed CT/CP values from lookup execution", false, false),
			new ReviewedGridInputField("reviewed_grid_slot_ready", "boolean", true,
					"reviewed grid slot manifest", "open only after reviewed CT/CP payload is present", false, false),
			new ReviewedGridInputField("runtime_coupling_allowed", "boolean", true,
					"runtime boundary", "keep lab manifest out of DronePhysics mutation", false, false),
			new ReviewedGridInputField("gameplay_auto_apply_allowed", "boolean", true,
					"playable boundary", "keep lab manifest out of gameplay auto tuning", false, false)
	);

	private PropellerArchiveCtCpJLookupReviewedGridInput() {
	}

	public record ReviewedGridInputField(
			String fieldName,
			String unit,
			boolean required,
			String source,
			String downstreamUse,
			boolean runtimeCouplingAllowed,
			boolean gameplayAutoApplyAllowed
	) {
	}

	public record ReviewedGridInputSlot(
			String presetName,
			String caseName,
			String performanceMatchId,
			String slotId,
			String slotKind,
			String slotCoordinateRole,
			double queryAdvanceRatioJ,
			double queryRpm,
			double slotAdvanceRatioJ,
			double slotRpm,
			int minimumPerformanceNeighborRows,
			String executionInputSourceKind,
			boolean directNeighborBindingReady,
			boolean scatteredFitRequired,
			boolean postReviewFullSimulationLookupAllowed,
			boolean archiveCurveShapeGuardPassed,
			int negativeThrustTailRowCount,
			double archiveCurveEtaFormulaResidual,
			double archiveCurveCtIncrease,
			boolean coefficientPayloadReviewed,
			boolean reviewedGridSlotReady,
			boolean runtimeCouplingAllowed,
			boolean gameplayAutoApplyAllowed,
			String status,
			String message
	) {
	}

	public record ReviewedGridInputSummary(
			int targetRowCount,
			int gridSlotRowCount,
			int staticAnchorSlotCount,
			int bilinearCornerSlotCount,
			int highDomainEdgeSlotCount,
			int directStaticAnchorSlotCount,
			int scatteredSurfaceFitSlotCount,
			int fullSimulationGridSlotCount,
			int performanceOnlyGridSlotCount,
			int archiveCurveShapeGuardReadySlotCount,
			int coefficientPayloadReviewedSlotCount,
			int reviewedGridSlotReadyCount,
			double minSlotAdvanceRatioJ,
			double maxSlotAdvanceRatioJ,
			double minSlotRpm,
			double maxSlotRpm,
			int runtimeCouplingAllowedCount,
			int gameplayAutoApplyAllowedCount,
			String nextRequiredAction
	) {
	}

	public record CtCpJLookupReviewedGridInputAudit(
			String sourceId,
			String caveat,
			int packetRowCount,
			int sourceReferenceRowCount,
			int gridInputFieldRowCount,
			int gridInputSlotRowCount,
			int summaryRowCount,
			int methodRowCount,
			List<ReviewedGridInputField> fields,
			List<ReviewedGridInputSlot> slots,
			ReviewedGridInputSummary summary
	) {
		public CtCpJLookupReviewedGridInputAudit {
			fields = List.copyOf(fields);
			slots = List.copyOf(slots);
		}
	}

	public static CtCpJLookupReviewedGridInputAudit audit() {
		List<ReviewedGridInputSlot> slots = new ArrayList<>();
		for (PropellerArchiveCtCpJScatteredSurfaceFitExecutionHandoff.ExecutionInputHandoffRow handoff
				: PropellerArchiveCtCpJScatteredSurfaceFitExecutionHandoff.audit().rows()) {
			slots.addAll(slots(handoff));
		}
		return new CtCpJLookupReviewedGridInputAudit(
				SOURCE_ID,
				CAVEAT,
				PACKET_ROW_COUNT,
				SOURCE_REFERENCE_ROW_COUNT,
				GRID_INPUT_FIELD_ROW_COUNT,
				GRID_INPUT_SLOT_ROW_COUNT,
				SUMMARY_ROW_COUNT,
				METHOD_ROW_COUNT,
				FIELDS,
				slots,
				summary(slots)
		);
	}

	public static ReviewedGridInputField field(String fieldName) {
		return FIELDS.stream()
				.filter(field -> field.fieldName().equals(fieldName))
				.findFirst()
				.orElseThrow(() -> new IllegalArgumentException(
						"unknown CT/CP/J reviewed grid input field: " + fieldName));
	}

	public static List<ReviewedGridInputSlot> slots(String presetName, String caseName) {
		return audit().slots()
				.stream()
				.filter(slot -> slot.presetName().equals(presetName) && slot.caseName().equals(caseName))
				.toList();
	}

	public static ReviewedGridInputSlot slot(String presetName, String caseName, String slotId) {
		return slots(presetName, caseName).stream()
				.filter(slot -> slot.slotId().equals(slotId))
				.findFirst()
				.orElseThrow(() -> new IllegalArgumentException(
						"unknown CT/CP/J reviewed grid input slot: "
								+ presetName + " / " + caseName + " / " + slotId));
	}

	private static List<ReviewedGridInputSlot> slots(
			PropellerArchiveCtCpJScatteredSurfaceFitExecutionHandoff.ExecutionInputHandoffRow handoff
	) {
		PropellerArchiveCtCpJLookupInterpolationPolicy.QueryInterpolationContract contract =
				PropellerArchiveCtCpJLookupInterpolationPolicy.contract(handoff.presetName(), handoff.caseName());
		PropellerArchiveCtCpJLookupSeed.PresetLookupSeed seed =
				PropellerArchiveCtCpJLookupSeed.preset(handoff.presetName());
		List<Double> advanceSlots = slotCoordinates(
				contract.queryAdvanceRatioJ(),
				seed.advanceRatioMin(),
				seed.advanceRatioMax(),
				contract.minimumAdvanceNeighbors());
		List<Double> rpmSlots = slotCoordinates(
				contract.queryRpm(),
				seed.rpmMin(),
				seed.rpmMax(),
				contract.minimumRpmNeighbors());
		List<ReviewedGridInputSlot> slots = new ArrayList<>();
		for (int rpmIndex = 0; rpmIndex < rpmSlots.size(); rpmIndex++) {
			for (int jIndex = 0; jIndex < advanceSlots.size(); jIndex++) {
				slots.add(slot(handoff, contract, advanceSlots, rpmSlots, jIndex, rpmIndex));
			}
		}
		return slots;
	}

	private static ReviewedGridInputSlot slot(
			PropellerArchiveCtCpJScatteredSurfaceFitExecutionHandoff.ExecutionInputHandoffRow handoff,
			PropellerArchiveCtCpJLookupInterpolationPolicy.QueryInterpolationContract contract,
			List<Double> advanceSlots,
			List<Double> rpmSlots,
			int jIndex,
			int rpmIndex
	) {
		String kind = slotKind(contract);
		String role = coordinateRole(advanceSlots, rpmSlots, jIndex, rpmIndex);
		boolean ready = handoff.coefficientPayloadReviewed() && handoff.executionInputReady();
		return new ReviewedGridInputSlot(
				handoff.presetName(),
				handoff.caseName(),
				handoff.performanceMatchId(),
				slotId(advanceSlots, rpmSlots, jIndex, rpmIndex),
				kind,
				role,
				contract.queryAdvanceRatioJ(),
				contract.queryRpm(),
				advanceSlots.get(jIndex),
				rpmSlots.get(rpmIndex),
				contract.minimumPerformanceNeighborRows(),
				handoff.executionInputSourceKind(),
				handoff.directNeighborBindingReady(),
				handoff.scatteredFitRequired(),
				handoff.postReviewFullSimulationLookupAllowed(),
				handoff.archiveCurveShapeGuardPassed(),
				handoff.negativeThrustTailRowCount(),
				handoff.archiveCurveEtaFormulaResidual(),
				handoff.archiveCurveCtIncrease(),
				handoff.coefficientPayloadReviewed(),
				ready,
				false,
				false,
				ready ? "READY" : "AWAIT_REVIEWED_COEFFICIENT_PAYLOAD",
				ready ? "reviewed-grid-slot-ready" : messageFor(kind));
	}

	private static String slotKind(
			PropellerArchiveCtCpJLookupInterpolationPolicy.QueryInterpolationContract contract
	) {
		if (contract.staticAnchorPreserved()) {
			return "DIRECT_STATIC_ANCHOR_SLOT";
		}
		if (contract.minimumAdvanceNeighbors() == 2 && contract.minimumRpmNeighbors() == 2) {
			return "BILINEAR_CORNER_SLOT";
		}
		if (contract.minimumAdvanceNeighbors() == 2 && contract.minimumRpmNeighbors() == 1) {
			return "HIGH_RPM_EDGE_SLOT";
		}
		return "LOOKUP_GRID_SLOT";
	}

	private static String slotId(List<Double> advanceSlots, List<Double> rpmSlots, int jIndex, int rpmIndex) {
		if (advanceSlots.size() == 1 && rpmSlots.size() == 1) {
			return "static-anchor";
		}
		String j = jIndex == 0 ? "j0" : "j1";
		String rpm = rpmSlots.size() == 1
				? "rmax"
				: rpmIndex == 0 ? "r0" : "r1";
		return j + "-" + rpm;
	}

	private static String coordinateRole(List<Double> advanceSlots, List<Double> rpmSlots, int jIndex, int rpmIndex) {
		if (advanceSlots.size() == 1 && rpmSlots.size() == 1) {
			return "query_j_query_rpm";
		}
		String j = jIndex == 0 ? "lower_j" : "upper_j";
		String rpm = rpmSlots.size() == 1
				? "query_rpm"
				: rpmIndex == 0 ? "lower_rpm" : "upper_rpm";
		return j + "_" + rpm;
	}

	private static List<Double> slotCoordinates(double query, double min, double max, int count) {
		if (count <= 0) {
			return List.of();
		}
		if (count == 1 || Math.abs(max - min) <= 1.0e-12) {
			return List.of(query);
		}
		double halfWidth = Math.max((max - min) * SLOT_HALF_WINDOW_FRACTION, 1.0e-12);
		double lower = query - halfWidth;
		double upper = query + halfWidth;
		if (lower < min) {
			upper = Math.min(max, min + 2.0 * halfWidth);
			lower = min;
		}
		if (upper > max) {
			lower = Math.max(min, max - 2.0 * halfWidth);
			upper = max;
		}
		return List.of(lower, upper);
	}

	private static ReviewedGridInputSummary summary(List<ReviewedGridInputSlot> slots) {
		int staticAnchors = 0;
		int bilinear = 0;
		int highEdge = 0;
		int direct = 0;
		int scattered = 0;
		int full = 0;
		int performanceOnly = 0;
		int shape = 0;
		int reviewed = 0;
		int ready = 0;
		int runtime = 0;
		int gameplay = 0;
		double minJ = Double.POSITIVE_INFINITY;
		double maxJ = 0.0;
		double minRpm = Double.POSITIVE_INFINITY;
		double maxRpm = 0.0;
		for (ReviewedGridInputSlot slot : slots) {
			if ("DIRECT_STATIC_ANCHOR_SLOT".equals(slot.slotKind())) {
				staticAnchors++;
			}
			if ("BILINEAR_CORNER_SLOT".equals(slot.slotKind())) {
				bilinear++;
			}
			if ("HIGH_RPM_EDGE_SLOT".equals(slot.slotKind())) {
				highEdge++;
			}
			if (slot.directNeighborBindingReady()) {
				direct++;
			}
			if (slot.scatteredFitRequired()) {
				scattered++;
			}
			if (slot.postReviewFullSimulationLookupAllowed()) {
				full++;
			} else {
				performanceOnly++;
			}
			if (slot.archiveCurveShapeGuardPassed()) {
				shape++;
			}
			if (slot.coefficientPayloadReviewed()) {
				reviewed++;
			}
			if (slot.reviewedGridSlotReady()) {
				ready++;
			}
			if (slot.runtimeCouplingAllowed()) {
				runtime++;
			}
			if (slot.gameplayAutoApplyAllowed()) {
				gameplay++;
			}
			minJ = Math.min(minJ, slot.slotAdvanceRatioJ());
			maxJ = Math.max(maxJ, slot.slotAdvanceRatioJ());
			minRpm = Math.min(minRpm, slot.slotRpm());
			maxRpm = Math.max(maxRpm, slot.slotRpm());
		}
		int targets = PropellerArchiveCtCpJScatteredSurfaceFitExecutionHandoff.audit().rows().size();
		return new ReviewedGridInputSummary(
				targets,
				slots.size(),
				staticAnchors,
				bilinear,
				highEdge,
				direct,
				scattered,
				full,
				performanceOnly,
				shape,
				reviewed,
				ready,
				minJ,
				maxJ,
				minRpm,
				maxRpm,
				runtime,
				gameplay,
				NEXT_REQUIRED_ACTION
		);
	}

	private static String messageFor(String kind) {
		if ("DIRECT_STATIC_ANCHOR_SLOT".equals(kind)) {
			return "await-reviewed-static-anchor-ct-cp-payload";
		}
		if ("HIGH_RPM_EDGE_SLOT".equals(kind)) {
			return "await-reviewed-high-rpm-edge-ct-cp-payload";
		}
		return "await-reviewed-bilinear-corner-ct-cp-payload";
	}
}
