package com.tenicana.dronecraft.sim.flight;

public enum StateCorrectionReason {
	NONE,
	NORMAL_INTEGRATION,
	COLLISION_CONTACT_SOLVE,
	RESET_TELEPORT,
	NETWORK_CORRECTION,
	COMPLETED_ROLL_VELOCITY_TRIM,
	ASSISTED_LEVEL_RECOVERY,
	SPEED_ENVELOPE_LIMIT,
	GROUND_STABILIZATION,
	MODEL_INITIALIZATION,
	UNKNOWN_LEGACY
}
