package com.tenicana.dronecraft.sim.tools;

import com.tenicana.dronecraft.sim.PropellerArchiveCtCpJDimensionalRotorResponse;
import com.tenicana.dronecraft.sim.PropellerArchiveCtCpJLookupEvaluator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class CtCpJActuatorDiskOpenFoamSampleDictExporter {
	private CtCpJActuatorDiskOpenFoamSampleDictExporter() {
	}

	public static void main(String[] args) throws IOException {
		String presetName = args.length >= 1 && !args[0].isBlank()
				? args[0]
				: PropellerArchiveCtCpJLookupEvaluator.DEFAULT_PRESET_NAME;
		Path output = args.length >= 2 && !args[1].isBlank()
				? Path.of(args[1])
				: Path.of("build", "ct-cp-j-actuator-disk-wake-probes", presetName + "-openfoam-sampleDict");
		double airDensity = args.length >= 3 && !args[2].isBlank()
				? Double.parseDouble(args[2])
				: PropellerArchiveCtCpJDimensionalRotorResponse.STANDARD_AIR_DENSITY_KG_PER_CUBIC_METER;
		double sourceThickness = args.length >= 4 && !args[3].isBlank()
				? Double.parseDouble(args[3])
				: CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS;
		double ambientTemperatureCelsius = args.length >= 5 && !args[4].isBlank()
				? Double.parseDouble(args[4])
				: 25.0;
		double ambientHumidity = args.length >= 6 && !args[5].isBlank()
				? Double.parseDouble(args[5])
				: 0.0;
		write(
				presetName,
				output,
				airDensity,
				sourceThickness,
				ambientTemperatureCelsius,
				ambientHumidity
		);
	}

	public static void write(
			String presetName,
			Path output,
			double airDensityKgPerCubicMeter
	) throws IOException {
		write(
				presetName,
				output,
				airDensityKgPerCubicMeter,
				CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS,
				25.0,
				0.0
		);
	}

	public static void write(
			String presetName,
			Path output,
			double airDensityKgPerCubicMeter,
			double sourceThicknessMeters,
			double ambientTemperatureCelsius,
			double ambientHumidity
	) throws IOException {
		if (output == null) {
			throw new IllegalArgumentException("output path must not be null.");
		}
		Path parent = output.toAbsolutePath().getParent();
		if (parent != null) {
			Files.createDirectories(parent);
		}
		Files.writeString(output, sampleDict(
				presetName,
				airDensityKgPerCubicMeter,
				sourceThicknessMeters,
				ambientTemperatureCelsius,
				ambientHumidity), StandardCharsets.UTF_8);
	}

	public static String sampleDict(
			String presetName,
			double airDensityKgPerCubicMeter
	) {
		return sampleDict(
				presetName,
				airDensityKgPerCubicMeter,
				CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS,
				25.0,
				0.0
		);
	}

	public static String sampleDict(
			String presetName,
			double airDensityKgPerCubicMeter,
			double sourceThicknessMeters,
			double ambientTemperatureCelsius,
			double ambientHumidity
	) {
		List<Map<String, String>> centerlineRows = parseCsv(String.join("\n",
				CtCpJActuatorDiskWakeProbeExporter.csvLines(
						presetName,
						airDensityKgPerCubicMeter,
						sourceThicknessMeters,
						ambientTemperatureCelsius,
						ambientHumidity
				)));
		List<Map<String, String>> wakePlaneRows = parseCsv(String.join("\n",
				CtCpJActuatorDiskWakePlaneProbeExporter.csvLines(
						presetName,
						airDensityKgPerCubicMeter,
						sourceThicknessMeters,
						ambientTemperatureCelsius,
						ambientHumidity
				)));
		Map<String, List<Map<String, String>>> centerlineBySource = groupBySource(centerlineRows);
		Map<String, List<Map<String, String>>> wakePlaneBySource = groupBySource(wakePlaneRows);
		if (!centerlineBySource.keySet().equals(wakePlaneBySource.keySet())) {
			throw new IllegalStateException("centerline and wake-plane probe source keys do not match.");
		}

		StringBuilder builder = new StringBuilder();
		builder.append("/* Generated by CtCpJActuatorDiskOpenFoamSampleDictExporter.\n")
				.append("   Offline A4MC/OpenFOAM sampling only; not a Minecraft runtime dependency. */\n\n")
				.append("FoamFile\n")
				.append("{\n")
				.append("    version     2.0;\n")
				.append("    format      ascii;\n")
				.append("    class       dictionary;\n")
				.append("    object      sampleDict;\n")
				.append("}\n\n")
				.append("type sets;\n")
				.append("libs (\"libsampling.so\");\n")
				.append("interpolationScheme cellPoint;\n")
				.append("setFormat raw;\n\n")
				.append("fields\n")
				.append("(\n")
				.append("    U\n")
				.append("    p\n")
				.append(");\n\n")
				.append("sets\n")
				.append("(\n");
		boolean first = true;
		for (String sourceName : centerlineBySource.keySet()) {
			first = appendSet(
					builder,
					first,
					sanitize(sourceName + "_centerline"),
					"centerline_axial",
					centerlineBySource.get(sourceName)
			);
			first = appendSet(
					builder,
					first,
					sanitize(sourceName + "_wake_plane"),
					"wake_plane_top_hat",
					wakePlaneBySource.get(sourceName)
			);
		}
		builder.append(");\n");
		return builder.toString();
	}

	private static boolean appendSet(
			StringBuilder builder,
			boolean first,
			String setName,
			String packetKind,
			List<Map<String, String>> rows
	) {
		if (rows == null || rows.isEmpty()) {
			throw new IllegalArgumentException("sample set " + setName + " must contain at least one row.");
		}
		Map<String, String> firstRow = rows.get(0);
		if (!first) {
			builder.append("\n");
		}
		builder.append("    // preset=").append(commentValue(text(firstRow, "preset")))
				.append(" case=").append(commentValue(text(firstRow, "case")))
				.append(" row_kind=").append(commentValue(text(firstRow, "row_kind")))
				.append(" rotor_index=").append(commentValue(text(firstRow, "rotor_index")))
				.append(" source_enabled=").append(commentValue(text(firstRow, "source_enabled")))
				.append(" lookup_status=").append(commentValue(text(firstRow, "lookup_status")))
				.append(" clamped=").append(commentValue(text(firstRow, "clamped")))
				.append(" blocked=").append(commentValue(text(firstRow, "blocked")))
				.append(" probe_packet=").append(packetKind)
				.append(" points=").append(rows.size())
				.append("\n");
		builder.append("    ").append(setName).append("\n")
				.append("    {\n")
				.append("        type    cloud;\n")
				.append("        axis    xyz;\n")
				.append("        points\n")
				.append("        (\n");
		for (Map<String, String> row : rows) {
			builder.append("            (")
					.append(required(row, "probe_point_world_x_m"))
					.append(" ")
					.append(required(row, "probe_point_world_y_m"))
					.append(" ")
					.append(required(row, "probe_point_world_z_m"))
					.append(")\n");
		}
		builder.append("        );\n")
				.append("    }\n");
		return false;
	}

	private static Map<String, List<Map<String, String>>> groupBySource(List<Map<String, String>> rows) {
		Map<String, List<Map<String, String>>> grouped = new LinkedHashMap<>();
		for (Map<String, String> row : rows) {
			grouped.computeIfAbsent(required(row, "source_name"), ignored -> new ArrayList<>()).add(row);
		}
		return grouped;
	}

	private static List<Map<String, String>> parseCsv(String inputCsv) {
		List<List<String>> rawRows = new ArrayList<>();
		for (String line : inputCsv.split("\\R")) {
			if (line == null || line.isBlank()) {
				continue;
			}
			rawRows.add(parseCsvLine(line));
		}
		if (rawRows.isEmpty()) {
			return List.of();
		}
		List<String> header = rawRows.get(0).stream()
				.map(CtCpJActuatorDiskOpenFoamSampleDictExporter::normalizeHeader)
				.toList();
		List<Map<String, String>> records = new ArrayList<>();
		for (int rowIndex = 1; rowIndex < rawRows.size(); rowIndex++) {
			Map<String, String> record = new LinkedHashMap<>();
			List<String> cells = rawRows.get(rowIndex);
			for (int column = 0; column < header.size(); column++) {
				record.put(header.get(column), column < cells.size() ? cells.get(column).trim() : "");
			}
			records.add(record);
		}
		return records;
	}

	private static List<String> parseCsvLine(String line) {
		List<String> cells = new ArrayList<>();
		StringBuilder cell = new StringBuilder();
		boolean quoted = false;
		for (int i = 0; i < line.length(); i++) {
			char ch = line.charAt(i);
			if (quoted) {
				if (ch == '"') {
					if (i + 1 < line.length() && line.charAt(i + 1) == '"') {
						cell.append('"');
						i++;
					} else {
						quoted = false;
					}
				} else {
					cell.append(ch);
				}
			} else if (ch == '"') {
				quoted = true;
			} else if (ch == ',') {
				cells.add(cell.toString());
				cell.setLength(0);
			} else {
				cell.append(ch);
			}
		}
		cells.add(cell.toString());
		return cells;
	}

	private static String normalizeHeader(String value) {
		String normalized = value == null ? "" : value.trim().toLowerCase(Locale.ROOT);
		if (!normalized.isEmpty() && normalized.charAt(0) == '\uFEFF') {
			normalized = normalized.substring(1);
		}
		return normalized;
	}

	private static String required(Map<String, String> row, String columnName) {
		String value = text(row, columnName);
		if (value.isBlank()) {
			throw new IllegalArgumentException("required column is blank: " + columnName);
		}
		return value;
	}

	private static String text(Map<String, String> row, String columnName) {
		return row.getOrDefault(columnName, "");
	}

	private static String sanitize(String value) {
		StringBuilder builder = new StringBuilder();
		for (int i = 0; i < value.length(); i++) {
			char ch = Character.toLowerCase(value.charAt(i));
			if ((ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')) {
				builder.append(ch);
			} else if (builder.length() == 0 || builder.charAt(builder.length() - 1) != '_') {
				builder.append('_');
			}
		}
		while (builder.length() > 0 && builder.charAt(builder.length() - 1) == '_') {
			builder.setLength(builder.length() - 1);
		}
		return builder.toString();
	}

	private static String commentValue(String value) {
		return value.replace('\r', ' ')
				.replace('\n', ' ')
				.replace("*/", "* /");
	}
}
