package com.tenicana.dronecraft.sim.tools;

import com.tenicana.dronecraft.sim.PropellerArchiveCtCpJDimensionalRotorResponse;
import com.tenicana.dronecraft.sim.PropellerArchiveCtCpJLookupEvaluator;
import com.tenicana.dronecraft.sim.Vec3;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class CtCpJActuatorDiskOpenFoamCaseDictExporter {
	private CtCpJActuatorDiskOpenFoamCaseDictExporter() {
	}

	public record OpenFoamCaseDicts(String topoSetDict, String fvOptions) {
	}

	public static void main(String[] args) throws IOException {
		String presetName = args.length >= 1 && !args[0].isBlank()
				? args[0]
				: PropellerArchiveCtCpJLookupEvaluator.DEFAULT_PRESET_NAME;
		Path outputDirectory = args.length >= 2 && !args[1].isBlank()
				? Path.of(args[1])
				: Path.of("build", "ct-cp-j-actuator-disk-openfoam-case", presetName);
		double airDensity = args.length >= 3 && !args[2].isBlank()
				? Double.parseDouble(args[2])
				: PropellerArchiveCtCpJDimensionalRotorResponse.STANDARD_AIR_DENSITY_KG_PER_CUBIC_METER;
		double sourceThickness = args.length >= 4 && !args[3].isBlank()
				? Double.parseDouble(args[3])
				: CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS;
		double ambientTemperatureCelsius = args.length >= 5 && !args[4].isBlank()
				? Double.parseDouble(args[4])
				: 25.0;
		double ambientHumidity = args.length >= 6 && !args[5].isBlank()
				? Double.parseDouble(args[5])
				: 0.0;
		write(
				presetName,
				outputDirectory,
				airDensity,
				sourceThickness,
				ambientTemperatureCelsius,
				ambientHumidity
		);
	}

	public static void write(
			String presetName,
			Path outputDirectory,
			double airDensityKgPerCubicMeter
	) throws IOException {
		write(
				presetName,
				outputDirectory,
				airDensityKgPerCubicMeter,
				CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS,
				25.0,
				0.0
		);
	}

	public static void write(
			String presetName,
			Path outputDirectory,
			double airDensityKgPerCubicMeter,
			double sourceThicknessMeters,
			double ambientTemperatureCelsius,
			double ambientHumidity
	) throws IOException {
		if (outputDirectory == null) {
			throw new IllegalArgumentException("outputDirectory must not be null.");
		}
		OpenFoamCaseDicts dicts = dicts(
				presetName,
				airDensityKgPerCubicMeter,
				sourceThicknessMeters,
				ambientTemperatureCelsius,
				ambientHumidity
		);
		Files.createDirectories(outputDirectory);
		Files.writeString(outputDirectory.resolve("topoSetDict"), dicts.topoSetDict(), StandardCharsets.UTF_8);
		Files.writeString(outputDirectory.resolve("fvOptions"), dicts.fvOptions(), StandardCharsets.UTF_8);
	}

	public static OpenFoamCaseDicts dicts(
			String presetName,
			double airDensityKgPerCubicMeter
	) {
		return dicts(
				presetName,
				airDensityKgPerCubicMeter,
				CtCpJActuatorDiskSourceTermExporter.DEFAULT_SOURCE_THICKNESS_METERS,
				25.0,
				0.0
		);
	}

	public static OpenFoamCaseDicts dicts(
			String presetName,
			double airDensityKgPerCubicMeter,
			double sourceThicknessMeters,
			double ambientTemperatureCelsius,
			double ambientHumidity
	) {
		if (!Double.isFinite(airDensityKgPerCubicMeter) || airDensityKgPerCubicMeter <= 0.0) {
			throw new IllegalArgumentException("airDensityKgPerCubicMeter must be finite and positive.");
		}
		List<Map<String, String>> rows = parseCsv(String.join("\n",
				CtCpJActuatorDiskOpenFoamSourceTableExporter.csvLines(
						presetName,
						airDensityKgPerCubicMeter,
						sourceThicknessMeters,
						ambientTemperatureCelsius,
						ambientHumidity
				)));
		return new OpenFoamCaseDicts(topoSetDict(rows), fvOptions(rows, airDensityKgPerCubicMeter));
	}

	private static String topoSetDict(List<Map<String, String>> rows) {
		StringBuilder builder = new StringBuilder();
		builder.append("/* Generated by CtCpJActuatorDiskOpenFoamCaseDictExporter.\n")
				.append("   Offline OpenFOAM case material only; not a Minecraft runtime dependency. */\n\n")
				.append(foamFile("dictionary", "topoSetDict"))
				.append("\n")
				.append("actions\n")
				.append("(\n");
		for (Map<String, String> row : rows) {
			String sourceName = required(row, "source_name");
			builder.append("    // preset=").append(commentValue(text(row, "preset")))
					.append(" case=").append(commentValue(text(row, "case")))
					.append(" row_kind=").append(commentValue(text(row, "row_kind")))
					.append(" rotor_index=").append(commentValue(text(row, "rotor_index")))
					.append(" source_enabled=").append(commentValue(text(row, "source_enabled")))
					.append(" lookup_status=").append(commentValue(text(row, "lookup_status")))
					.append(" clamped=").append(commentValue(text(row, "clamped")))
					.append(" blocked=").append(commentValue(text(row, "blocked")))
					.append("\n")
					.append("    {\n")
					.append("        name    ").append(cellSetName(sourceName)).append(";\n")
					.append("        type    cellSet;\n")
					.append("        action  new;\n")
					.append("        source  cylinderToCell;\n")
					.append("        p1      ").append(vector(row, "axis_min_x_m", "axis_min_y_m", "axis_min_z_m"))
					.append(";\n")
					.append("        p2      ").append(vector(row, "axis_max_x_m", "axis_max_y_m", "axis_max_z_m"))
					.append(";\n")
					.append("        radius  ").append(value(row, "radius_m")).append(";\n")
					.append("    }\n\n");
		}
		builder.append(");\n");
		return builder.toString();
	}

	private static String fvOptions(List<Map<String, String>> rows, double airDensityKgPerCubicMeter) {
		StringBuilder builder = new StringBuilder();
		builder.append("/* Generated by CtCpJActuatorDiskOpenFoamCaseDictExporter.\n")
				.append("   U sources are incompressible acceleration terms: body_force_density_n_m3 / rho.\n")
				.append("   Confirm solver fvOptions dimensions before using in a production case. */\n\n")
				.append(foamFile("dictionary", "fvOptions"))
				.append("\n");
		for (Map<String, String> row : rows) {
			String sourceName = required(row, "source_name");
			Vec3 bodyForceDensity = new Vec3(
					number(row, "body_force_density_x_n_m3"),
					number(row, "body_force_density_y_n_m3"),
					number(row, "body_force_density_z_n_m3")
			);
			Vec3 acceleration = bodyForceDensity.multiply(1.0 / airDensityKgPerCubicMeter);
			if (!Boolean.parseBoolean(text(row, "source_enabled"))) {
				builder.append("// disabled source: ").append(sourceName)
						.append(" lookup_status=").append(commentValue(text(row, "lookup_status")))
						.append(" blocked=").append(commentValue(text(row, "blocked")))
						.append("\n\n");
				continue;
			}
			builder.append("// source=").append(sourceName)
					.append(" body_force_density_n_m3=").append(vec(bodyForceDensity))
					.append(" acceleration_m_s2=").append(vec(acceleration))
					.append("\n")
					.append(momentumSourceName(sourceName)).append("\n")
					.append("{\n")
					.append("    type            vectorSemiImplicitSource;\n")
					.append("    active          yes;\n")
					.append("    vectorSemiImplicitSourceCoeffs\n")
					.append("    {\n")
					.append("        selectionMode   cellSet;\n")
					.append("        cellSet         ").append(cellSetName(sourceName)).append(";\n")
					.append("        volumeMode      specific;\n")
					.append("        injectionRateSuSp\n")
					.append("        {\n")
					.append("            U           (").append(vec(acceleration)).append(" 0);\n")
					.append("        }\n")
					.append("    }\n")
					.append("}\n\n");
		}
		return builder.toString();
	}

	private static String foamFile(String className, String objectName) {
		return "FoamFile\n"
				+ "{\n"
				+ "    version     2.0;\n"
				+ "    format      ascii;\n"
				+ "    class       " + className + ";\n"
				+ "    object      " + objectName + ";\n"
				+ "}\n";
	}

	private static String cellSetName(String sourceName) {
		return sanitize(sourceName + "_cells");
	}

	private static String momentumSourceName(String sourceName) {
		return sanitize(sourceName + "_u_source");
	}

	private static List<Map<String, String>> parseCsv(String inputCsv) {
		List<List<String>> rawRows = new ArrayList<>();
		for (String line : inputCsv.split("\\R")) {
			if (line == null || line.isBlank()) {
				continue;
			}
			rawRows.add(parseCsvLine(line));
		}
		if (rawRows.isEmpty()) {
			return List.of();
		}
		List<String> header = rawRows.get(0).stream()
				.map(CtCpJActuatorDiskOpenFoamCaseDictExporter::normalizeHeader)
				.toList();
		List<Map<String, String>> records = new ArrayList<>();
		for (int rowIndex = 1; rowIndex < rawRows.size(); rowIndex++) {
			Map<String, String> record = new LinkedHashMap<>();
			List<String> cells = rawRows.get(rowIndex);
			for (int column = 0; column < header.size(); column++) {
				record.put(header.get(column), column < cells.size() ? cells.get(column).trim() : "");
			}
			records.add(record);
		}
		return records;
	}

	private static List<String> parseCsvLine(String line) {
		List<String> cells = new ArrayList<>();
		StringBuilder cell = new StringBuilder();
		boolean quoted = false;
		for (int i = 0; i < line.length(); i++) {
			char ch = line.charAt(i);
			if (quoted) {
				if (ch == '"') {
					if (i + 1 < line.length() && line.charAt(i + 1) == '"') {
						cell.append('"');
						i++;
					} else {
						quoted = false;
					}
				} else {
					cell.append(ch);
				}
			} else if (ch == '"') {
				quoted = true;
			} else if (ch == ',') {
				cells.add(cell.toString());
				cell.setLength(0);
			} else {
				cell.append(ch);
			}
		}
		cells.add(cell.toString());
		return cells;
	}

	private static String normalizeHeader(String value) {
		String normalized = value == null ? "" : value.trim().toLowerCase(Locale.ROOT);
		if (!normalized.isEmpty() && normalized.charAt(0) == '\uFEFF') {
			normalized = normalized.substring(1);
		}
		return normalized;
	}

	private static String vector(Map<String, String> row, String x, String y, String z) {
		return "(" + value(row, x) + " " + value(row, y) + " " + value(row, z) + ")";
	}

	private static String vec(Vec3 value) {
		return "(" + number(value.x()) + " " + number(value.y()) + " " + number(value.z()) + ")";
	}

	private static String value(Map<String, String> row, String columnName) {
		return number(number(row, columnName));
	}

	private static double number(Map<String, String> row, String columnName) {
		return Double.parseDouble(required(row, columnName));
	}

	private static String number(double value) {
		return Double.isFinite(value) ? String.format(Locale.ROOT, "%.15g", value) : "";
	}

	private static String required(Map<String, String> row, String columnName) {
		String value = text(row, columnName);
		if (value.isBlank()) {
			throw new IllegalArgumentException("required column is blank: " + columnName);
		}
		return value;
	}

	private static String text(Map<String, String> row, String columnName) {
		return row.getOrDefault(columnName, "");
	}

	private static String sanitize(String value) {
		StringBuilder builder = new StringBuilder();
		for (int i = 0; i < value.length(); i++) {
			char ch = Character.toLowerCase(value.charAt(i));
			if ((ch >= 'a' && ch <= 'z') || (ch >= '0' && ch <= '9')) {
				builder.append(ch);
			} else if (builder.length() == 0 || builder.charAt(builder.length() - 1) != '_') {
				builder.append('_');
			}
		}
		while (builder.length() > 0 && builder.charAt(builder.length() - 1) == '_') {
			builder.setLength(builder.length() - 1);
		}
		return builder.toString();
	}

	private static String commentValue(String value) {
		return value.replace('\r', ' ')
				.replace('\n', ' ')
				.replace("*/", "* /");
	}
}
